[ui]
default-command = "log"
editor = "vim"

[colors]
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

[user]
name = "D"
email = "dector@dector.space"

[aliases]
clone = ["git", "clone"]
g = ["git"]
push = ["git", "push"]

