[tools]
bun = "latest"
java = "latest"
"ubi:block/goose" = "latest"
atuin = "latest"
zig = "latest"
"ubi:tailwindlabs/tailwindcss" = "latest"
deno = "latest"
starship = "latest"
uv = "latest"
"ubi:leoafarias/fvm" = "latest"
node = "latest"
jj = "latest"
zellij = "latest"
lazygit = "latest"
"ubi:idursun/jjui" = "latest"
"ubi:dector/bang" = "latest"
"ubi:dector/serv" = "latest"
bat = "latest"
"ubi:dector/lampa" = "latest"
"ubi:afnanenayet/diffsitter" = "latest"
claude = "latest"
"npm:@github/copilot" = "latest"
chezmoi = "latest"
task = "latest"
"ubi:umlx5h/gtrash" = "latest"
glow = "latest"
go = "latest"
"ubi:abenz1267/walker" = "latest"
yazi = "latest"
"ubi:tinygo-org/tinygo" = "latest"
"ubi:kainctl/isd" = "latest"
"ubi:fujiapple852/trippy" = { version = "latest", exe = "trip" }
"npm:vite" = "latest"
pnpm = "latest"
"ubi:neovim/neovim" = { version = "latest", exe = "nvim" }
"ubi:golangci/golangci-lint" = "latest"
"ubi:emprcl/runal" = "latest"
hk = "latest"
gemini = "latest"
